version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:yBwMjPplkIacDlyh9xxRCpfU+iNG/B84ItvZyAZq7co"
      - checkout
      - run:  ssh -l client 188.242.194.155 "/var/www/html/script"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:    
    jobs:
      - pull-and-build:
          steps:         
            filters:
              branches:
                only:
                - master
                
